<ul>
    <li class="helm unique">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/59" data-tooltip="Strength_Item : 154&lt;br&gt;Intelligence_Item : 65&lt;br&gt;Item_Power_Passive#itemPassive_Unique_Helm_003 : 0.26&lt;br&gt;Crit_Percent_Bonus_Capped : 0.045&lt;br&gt;Durability_Cur : 181&lt;br&gt;Vitality_Item : 69&lt;br&gt;Armor_Item : 387&lt;br&gt;Resistance#Poison : 46&lt;br&gt;Attacks_Per_Second_Percent : 0.09&lt;br&gt;Hitpoints_Regen_Per_Second : 188&lt;br&gt;Amplify_Damage_Type_Percent#Fire : 0.25&lt;br&gt;Durability_Max : 354&lt;br&gt;Crit_Percent_Bonus_Capped : 0.045&lt;br&gt;Intelligence_Item : 65&lt;br&gt;Attacks_Per_Second_Percent : 0.09&lt;br&gt;Amplify_Damage_Type_Percent#Fire : 0.25&lt;br&gt;Vitality_Item : 69&lt;br&gt;Durability_Max : 354&lt;br&gt;Strength_Item : 154&lt;br&gt;Armor_Item : 387&lt;br&gt;Hitpoints_Regen_Per_Second : 188&lt;br&gt;Item_Power_Passive#itemPassive_Unique_Helm_003 : 0.26&lt;br&gt;Durability_Cur : 181&lt;br&gt;Resistance#Poison : 46&lt;br&gt;Resistance#Poison : 46&lt;br&gt;Vitality_Item : 69&lt;br&gt;Durability_Max : 354&lt;br&gt;Durability_Cur : 181&lt;br&gt;Armor_Item : 387&lt;br&gt;Item_Power_Passive#itemPassive_Unique_Helm_003 : 0.26&lt;br&gt;Hitpoints_Regen_Per_Second : 188&lt;br&gt;Attacks_Per_Second_Percent : 0.09&lt;br&gt;Amplify_Damage_Type_Percent#Fire : 0.25&lt;br&gt;Crit_Percent_Bonus_Capped : 0.045&lt;br&gt;Strength_Item : 154&lt;br&gt;Intelligence_Item : 65&lt;br&gt;" data-tooltip-title="Andariel's Visage" class="nwTooltip" data-itemid="59" data-hasqtip="5" aria-describedby="qtip-5">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/unique_helm_003_104_demonhunter_male.png" class="helm unique" alt="Andariel's Visage">                                </a>
        </div>
    </li>
                                                                                <li class="chest ">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/60" data-tooltip="Strength_Item : 178&lt;br&gt;Vitality_Item : 160&lt;br&gt;Hitpoints_Regen_Per_Second : 370&lt;br&gt;Armor_Item : 422.5&lt;br&gt;Resistance_All : 76&lt;br&gt;Durability_Max : 659&lt;br&gt;Dexterity_Item : 72&lt;br&gt;Durability_Cur : 366&lt;br&gt;Gold_Find : 0.21&lt;br&gt;Dexterity_Item : 72&lt;br&gt;Vitality_Item : 160&lt;br&gt;Durability_Max : 659&lt;br&gt;Resistance_All : 76&lt;br&gt;Strength_Item : 178&lt;br&gt;Gold_Find : 0.21&lt;br&gt;Armor_Item : 422.5&lt;br&gt;Hitpoints_Regen_Per_Second : 370&lt;br&gt;Durability_Cur : 366&lt;br&gt;Strength_Item : 178&lt;br&gt;Durability_Max : 659&lt;br&gt;Armor_Item : 422.5&lt;br&gt;Hitpoints_Regen_Per_Second : 370&lt;br&gt;Vitality_Item : 160&lt;br&gt;Durability_Cur : 366&lt;br&gt;Dexterity_Item : 72&lt;br&gt;Resistance_All : 76&lt;br&gt;Gold_Find : 0.21&lt;br&gt;" data-tooltip-title="Carapace Rage" class="nwTooltip" data-itemid="60" data-hasqtip="6" aria-describedby="qtip-6">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/chestarmor_206_barbarian_male.png" class="chest " alt="Carapace Rage">                                </a>
        </div>
    </li>
                                                                                <li class="boots unique">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/61" data-tooltip="Intelligence_Item : 83&lt;br&gt;Armor_Item : 350.167&lt;br&gt;Strength_Item : 96&lt;br&gt;CrowdControl_Reduction : 0.13&lt;br&gt;Vitality_Item : 100&lt;br&gt;Durability_Cur : 236&lt;br&gt;Movement_Scalar : 0.12&lt;br&gt;Durability_Max : 445&lt;br&gt;Resistance_All : 77&lt;br&gt;Strength_Item : 96&lt;br&gt;Intelligence_Item : 83&lt;br&gt;Durability_Cur : 236&lt;br&gt;Vitality_Item : 100&lt;br&gt;Armor_Item : 350.167&lt;br&gt;CrowdControl_Reduction : 0.13&lt;br&gt;Movement_Scalar : 0.12&lt;br&gt;Resistance_All : 77&lt;br&gt;Durability_Max : 445&lt;br&gt;Strength_Item : 96&lt;br&gt;Durability_Cur : 236&lt;br&gt;Resistance_All : 77&lt;br&gt;Movement_Scalar : 0.12&lt;br&gt;CrowdControl_Reduction : 0.13&lt;br&gt;Armor_Item : 350.167&lt;br&gt;Vitality_Item : 100&lt;br&gt;Intelligence_Item : 83&lt;br&gt;Durability_Max : 445&lt;br&gt;" data-tooltip-title="Immortal King's Stride" class="nwTooltip" data-itemid="61" data-hasqtip="7">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/unique_boots_012_104_demonhunter_male.png" class="boots unique" alt="Immortal King's Stride">                                </a>
        </div>
    </li>
                                                                                <li class="gloves ">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/62" data-tooltip="Resistance_All : 75&lt;br&gt;Crit_Damage_Percent : 0.26&lt;br&gt;Armor_Item : 323.167&lt;br&gt;Durability_Cur : 306&lt;br&gt;Crit_Percent_Bonus_Capped : 0.1&lt;br&gt;Durability_Max : 559&lt;br&gt;Resistance#Cold : 53&lt;br&gt;Durability_Max : 559&lt;br&gt;Crit_Percent_Bonus_Capped : 0.1&lt;br&gt;Crit_Damage_Percent : 0.26&lt;br&gt;Resistance#Cold : 53&lt;br&gt;Resistance_All : 75&lt;br&gt;Armor_Item : 323.167&lt;br&gt;Durability_Cur : 306&lt;br&gt;Crit_Damage_Percent : 0.26&lt;br&gt;Resistance_All : 75&lt;br&gt;Armor_Item : 323.167&lt;br&gt;Resistance#Cold : 53&lt;br&gt;Crit_Percent_Bonus_Capped : 0.1&lt;br&gt;Durability_Cur : 306&lt;br&gt;Durability_Max : 559&lt;br&gt;" data-tooltip-title="Severe Fists" class="nwTooltip" data-itemid="62" data-hasqtip="8" aria-describedby="qtip-8">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/gloves_206_barbarian_male.png" class="gloves " alt="Severe Fists">                                </a>
        </div>
    </li>
                                                                                <li class="shoulders ">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/63" data-tooltip="Durability_Cur : 342&lt;br&gt;Resistance#Arcane : 54&lt;br&gt;Thorns_Fixed#Physical : 1218&lt;br&gt;Resistance_All : 79&lt;br&gt;Strength_Item : 269&lt;br&gt;Armor_Item : 390.333&lt;br&gt;Dexterity_Item : 44&lt;br&gt;Durability_Max : 623&lt;br&gt;Armor_Item : 390.333&lt;br&gt;Strength_Item : 269&lt;br&gt;Thorns_Fixed#Physical : 1218&lt;br&gt;Durability_Cur : 342&lt;br&gt;Dexterity_Item : 44&lt;br&gt;Durability_Max : 623&lt;br&gt;Resistance#Arcane : 54&lt;br&gt;Resistance_All : 79&lt;br&gt;Resistance#Arcane : 54&lt;br&gt;Resistance_All : 79&lt;br&gt;Strength_Item : 269&lt;br&gt;Armor_Item : 390.333&lt;br&gt;Dexterity_Item : 44&lt;br&gt;Durability_Cur : 342&lt;br&gt;Thorns_Fixed#Physical : 1218&lt;br&gt;Durability_Max : 623&lt;br&gt;" data-tooltip-title="Fierce Brace" class="nwTooltip" data-itemid="63" data-hasqtip="9" aria-describedby="qtip-9">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/shoulders_206_barbarian_male.png" class="shoulders " alt="Fierce Brace">                                </a>
        </div>
    </li>
                                                                                <li class="pants ">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/64" data-tooltip="Resistance_All : 69&lt;br&gt;Armor_Item : 432.5&lt;br&gt;Durability_Cur : 372&lt;br&gt;Dexterity_Item : 59&lt;br&gt;Strength_Item : 134&lt;br&gt;Durability_Max : 669&lt;br&gt;Vitality_Item : 197&lt;br&gt;Strength_Item : 134&lt;br&gt;Armor_Item : 432.5&lt;br&gt;Durability_Max : 669&lt;br&gt;Resistance_All : 69&lt;br&gt;Vitality_Item : 197&lt;br&gt;Dexterity_Item : 59&lt;br&gt;Durability_Cur : 372&lt;br&gt;Resistance_All : 69&lt;br&gt;Armor_Item : 432.5&lt;br&gt;Vitality_Item : 197&lt;br&gt;Strength_Item : 134&lt;br&gt;Durability_Cur : 372&lt;br&gt;Dexterity_Item : 59&lt;br&gt;Durability_Max : 669&lt;br&gt;" data-tooltip-title="Giant Robes" class="nwTooltip" data-itemid="64" data-hasqtip="10">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/pants_206_barbarian_male.png" class="pants " alt="Giant Robes">                                </a>
        </div>
    </li>
                                                                                <li class="bracer unique">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/65" data-tooltip="Durability_Max : 284&lt;br&gt;Vitality_Item : 74&lt;br&gt;Attacks_Per_Second_Percent : 0.09&lt;br&gt;Movement_Scalar : 0.12&lt;br&gt;Resistance#Lightning : 46&lt;br&gt;Strength_Item : 84&lt;br&gt;Thorns_Fixed#Physical : 1307&lt;br&gt;Armor_Item : 235.833&lt;br&gt;Durability_Cur : 139&lt;br&gt;Durability_Max : 284&lt;br&gt;Vitality_Item : 74&lt;br&gt;Attacks_Per_Second_Percent : 0.09&lt;br&gt;Movement_Scalar : 0.12&lt;br&gt;Resistance#Lightning : 46&lt;br&gt;Strength_Item : 84&lt;br&gt;Thorns_Fixed#Physical : 1307&lt;br&gt;Armor_Item : 235.833&lt;br&gt;Durability_Cur : 139&lt;br&gt;Thorns_Fixed#Physical : 1307&lt;br&gt;Strength_Item : 84&lt;br&gt;Resistance#Lightning : 46&lt;br&gt;Durability_Cur : 139&lt;br&gt;Movement_Scalar : 0.12&lt;br&gt;Armor_Item : 235.833&lt;br&gt;Attacks_Per_Second_Percent : 0.09&lt;br&gt;Vitality_Item : 74&lt;br&gt;Durability_Max : 284&lt;br&gt;" data-tooltip-title="Lacuni Prowlers" class="nwTooltip" data-itemid="65" data-hasqtip="11" aria-describedby="qtip-11">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/unique_bracer_005_104_demonhunter_male.png" class="bracer unique" alt="Lacuni Prowlers">                                </a>
        </div>
    </li>
                                                                                <li class="mace ">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/66" data-tooltip="Sockets : 1&lt;br&gt;Damage_Weapon_Min#Physical : 189&lt;br&gt;Durability_Cur : 391&lt;br&gt;Strength_Item : 191&lt;br&gt;Damage_Weapon_Delta#Physical : 162&lt;br&gt;Damage_Weapon_Bonus_Delta#Physical : 371&lt;br&gt;Durability_Max : 704&lt;br&gt;Damage_Weapon_Percent_Bonus#Physical : 0.46&lt;br&gt;Attacks_Per_Second_Item : 1.2&lt;br&gt;Damage_Weapon_Bonus_Min#Physical : 218&lt;br&gt;Dexterity_Item : 111&lt;br&gt;Damage_Weapon_Min#Physical : 189&lt;br&gt;Damage_Weapon_Delta#Physical : 162&lt;br&gt;Strength_Item : 191&lt;br&gt;Attacks_Per_Second_Item : 1.2&lt;br&gt;Sockets : 1&lt;br&gt;Damage_Weapon_Bonus_Delta#Physical : 371&lt;br&gt;Damage_Weapon_Percent_Bonus#Physical : 0.46&lt;br&gt;Damage_Weapon_Bonus_Min#Physical : 218&lt;br&gt;Durability_Cur : 391&lt;br&gt;Dexterity_Item : 111&lt;br&gt;Durability_Max : 704&lt;br&gt;Strength_Item : 191&lt;br&gt;Sockets : 1&lt;br&gt;Damage_Weapon_Delta#Physical : 162&lt;br&gt;Damage_Weapon_Bonus_Delta#Physical : 371&lt;br&gt;Damage_Weapon_Bonus_Min#Physical : 218&lt;br&gt;Durability_Cur : 391&lt;br&gt;Damage_Weapon_Percent_Bonus#Physical : 0.46&lt;br&gt;Damage_Weapon_Min#Physical : 189&lt;br&gt;Durability_Max : 704&lt;br&gt;Dexterity_Item : 111&lt;br&gt;Attacks_Per_Second_Item : 1.2&lt;br&gt;" data-tooltip-title="Slaughter Abyss" class="nwTooltip" data-itemid="66" data-hasqtip="12">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/mace_1h_207_demonhunter_male.png" class="mace " alt="Slaughter Abyss">                                </a>
        </div>
    </li>
                                                                                <li class="sword ">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/67" data-tooltip="Steal_Health_Percent : 0.03&lt;br&gt;Durability_Cur : 297&lt;br&gt;Damage_Weapon_Min#Physical : 106&lt;br&gt;Damage_Weapon_Min#Arcane : 232&lt;br&gt;Damage_Weapon_Delta#Arcane : 364&lt;br&gt;Hitpoints_On_Hit : 407&lt;br&gt;Sockets : 1&lt;br&gt;Durability_Max : 550&lt;br&gt;Vitality_Item : 178&lt;br&gt;Attacks_Per_Second_Item : 1.4&lt;br&gt;Damage_Weapon_Delta#Physical : 140&lt;br&gt;Hitpoints_On_Hit : 407&lt;br&gt;Damage_Weapon_Min#Physical : 106&lt;br&gt;Damage_Weapon_Min#Arcane : 232&lt;br&gt;Steal_Health_Percent : 0.03&lt;br&gt;Attacks_Per_Second_Item : 1.4&lt;br&gt;Damage_Weapon_Delta#Physical : 140&lt;br&gt;Durability_Cur : 297&lt;br&gt;Durability_Max : 550&lt;br&gt;Damage_Weapon_Delta#Arcane : 364&lt;br&gt;Sockets : 1&lt;br&gt;Vitality_Item : 178&lt;br&gt;Steal_Health_Percent : 0.03&lt;br&gt;Sockets : 1&lt;br&gt;Damage_Weapon_Delta#Physical : 140&lt;br&gt;Durability_Cur : 297&lt;br&gt;Damage_Weapon_Min#Arcane : 232&lt;br&gt;Damage_Weapon_Delta#Arcane : 364&lt;br&gt;Hitpoints_On_Hit : 407&lt;br&gt;Damage_Weapon_Min#Physical : 106&lt;br&gt;Vitality_Item : 178&lt;br&gt;Durability_Max : 550&lt;br&gt;Attacks_Per_Second_Item : 1.4&lt;br&gt;" data-tooltip-title="Discord Lux" class="nwTooltip" data-itemid="67" data-hasqtip="13">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/sword_1h_208_demonhunter_male.png" class="sword " alt="Discord Lux">                                </a>
        </div>
    </li>
                                                                                <li class="belt ">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/68" data-tooltip="Strength_Item : 197&lt;br&gt;Vitality_Item : 44&lt;br&gt;Steal_Health_Percent : 0.028&lt;br&gt;Armor_Item : 340&lt;br&gt;Resistance_All : 79&lt;br&gt;On_Hit_Freeze_Proc_Chance : 0.0272&lt;br&gt;Durability_Max : 455&lt;br&gt;Intelligence_Item : 64&lt;br&gt;Durability_Cur : 242&lt;br&gt;Thorns_Fixed#Physical : 1442&lt;br&gt;Strength_Item : 197&lt;br&gt;Vitality_Item : 44&lt;br&gt;Steal_Health_Percent : 0.028&lt;br&gt;Armor_Item : 340&lt;br&gt;Resistance_All : 79&lt;br&gt;On_Hit_Freeze_Proc_Chance : 0.0272&lt;br&gt;Durability_Max : 455&lt;br&gt;Intelligence_Item : 64&lt;br&gt;Durability_Cur : 242&lt;br&gt;Thorns_Fixed#Physical : 1442&lt;br&gt;Vitality_Item : 44&lt;br&gt;Steal_Health_Percent : 0.028&lt;br&gt;Thorns_Fixed#Physical : 1442&lt;br&gt;Intelligence_Item : 64&lt;br&gt;Resistance_All : 79&lt;br&gt;Durability_Cur : 242&lt;br&gt;Armor_Item : 340&lt;br&gt;Durability_Max : 455&lt;br&gt;On_Hit_Freeze_Proc_Chance : 0.0272&lt;br&gt;Strength_Item : 197&lt;br&gt;" data-tooltip-title="Undaunted Braid" class="nwTooltip" data-itemid="68" data-hasqtip="14">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/barbbelt_204_demonhunter_male.png" class="belt " alt="Undaunted Braid">                                </a>
        </div>
    </li>
                                                                                <li class="ring  ring-0" id="0">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/69" data-tooltip="Durability_Max : 377&lt;br&gt;Vitality_Item : 67&lt;br&gt;Crit_Percent_Bonus_Capped : 0.045&lt;br&gt;Attacks_Per_Second_Percent : 0.08&lt;br&gt;Damage_Delta#Physical : 20&lt;br&gt;Strength_Item : 67&lt;br&gt;Sockets : 1&lt;br&gt;Durability_Cur : 196&lt;br&gt;Sockets : 1&lt;br&gt;Attacks_Per_Second_Percent : 0.08&lt;br&gt;Crit_Percent_Bonus_Capped : 0.045&lt;br&gt;Durability_Cur : 196&lt;br&gt;Durability_Max : 377&lt;br&gt;Vitality_Item : 67&lt;br&gt;Strength_Item : 67&lt;br&gt;Damage_Delta#Physical : 20&lt;br&gt;Sockets : 1&lt;br&gt;Attacks_Per_Second_Percent : 0.08&lt;br&gt;Vitality_Item : 67&lt;br&gt;Strength_Item : 67&lt;br&gt;Durability_Max : 377&lt;br&gt;Durability_Cur : 196&lt;br&gt;Damage_Delta#Physical : 20&lt;br&gt;Crit_Percent_Bonus_Capped : 0.045&lt;br&gt;" class="nwTooltip" data-tooltip-title="Damnation Lash" data-hasqtip="15">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/ring_22_demonhunter_male.png" class="ring " alt="Damnation Lash">                                </a>
        </div>
    </li>
                                                                                                        <li class="ring unique ring-1" id="1">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/70" data-tooltip="Resistance_All : 55&lt;br&gt;Durability_Cur : 143&lt;br&gt;Strength_Item : 188&lt;br&gt;Experience_Bonus_Percent : 0.35&lt;br&gt;Damage_Delta#Physical : 24&lt;br&gt;Item_Power_Passive#ItemPassive_Unique_Ring_024 : 0.1&lt;br&gt;Damage_Min#Physical : 33&lt;br&gt;Hitpoints_Regen_Per_Second : 61&lt;br&gt;Durability_Max : 288&lt;br&gt;Damage_Bonus_Min#Physical : 19&lt;br&gt;Damage_Delta#Physical : 24&lt;br&gt;Item_Power_Passive#ItemPassive_Unique_Ring_024 : 0.1&lt;br&gt;Damage_Min#Physical : 33&lt;br&gt;Damage_Bonus_Min#Physical : 19&lt;br&gt;Experience_Bonus_Percent : 0.35&lt;br&gt;Durability_Max : 288&lt;br&gt;Resistance_All : 55&lt;br&gt;Strength_Item : 188&lt;br&gt;Hitpoints_Regen_Per_Second : 61&lt;br&gt;Durability_Cur : 143&lt;br&gt;Experience_Bonus_Percent : 0.35&lt;br&gt;Durability_Max : 288&lt;br&gt;Item_Power_Passive#ItemPassive_Unique_Ring_024 : 0.1&lt;br&gt;Hitpoints_Regen_Per_Second : 61&lt;br&gt;Damage_Delta#Physical : 24&lt;br&gt;Resistance_All : 55&lt;br&gt;Damage_Bonus_Min#Physical : 19&lt;br&gt;Durability_Cur : 143&lt;br&gt;Strength_Item : 188&lt;br&gt;Damage_Min#Physical : 33&lt;br&gt;" class="nwTooltip" data-tooltip-title="Hellfire Ring" data-hasqtip="16">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/unique_ring_024_104_demonhunter_male.png" class="ring unique" alt="Hellfire Ring">                                </a>
        </div>
    </li>
                                                                                                        <li class="amulet ">
        <div class="icon">
            <a href="{{ URL::to('item/compare/') }}/71" data-tooltip="Strength_Item : 241&lt;br&gt;Durability_Max : 353&lt;br&gt;Crit_Percent_Bonus_Capped : 0.085&lt;br&gt;Damage_Delta#Physical : 33&lt;br&gt;Dexterity_Item : 79&lt;br&gt;Durability_Cur : 180&lt;br&gt;Crit_Percent_Bonus_Capped : 0.085&lt;br&gt;Durability_Cur : 180&lt;br&gt;Dexterity_Item : 79&lt;br&gt;Durability_Max : 353&lt;br&gt;Strength_Item : 241&lt;br&gt;Damage_Delta#Physical : 33&lt;br&gt;Damage_Delta#Physical : 33&lt;br&gt;Dexterity_Item : 79&lt;br&gt;Durability_Cur : 180&lt;br&gt;Crit_Percent_Bonus_Capped : 0.085&lt;br&gt;Strength_Item : 241&lt;br&gt;Durability_Max : 353&lt;br&gt;" data-tooltip-title="Trance Hate" class="nwTooltip" data-itemid="71" data-hasqtip="17">
            <img src="{{ URL::to('assets/img/d3/items/large/') }}/amulet13_demonhunter_male.png" class="amulet " alt="Trance Hate">                                </a>
        </div>
    </li>
                            </ul>
